service: hops 

provider:
  name: aws
  runtime: nodejs4.3

defaults:
  stage: dev
  region: eu-west-1

functions:
  hops:
    handler: handler.aws
    events:
      - http:
        path: hops/aws
        method: post