service: aws-hop 

provider:
  name: aws
  runtime: nodejs4.3

defaults:
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: handler.aws_hop
    events:
     - http:
         path: aws/aws_hop
         method: post